#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo
echo WARNING! This will overwrite the following in your ~ directory:
echo
echo "    .bash_profile"
echo "    .gitconfig"
echo "    .inputrc"
echo "    .jumpdests"
echo "    .tmux.conf"
echo "    .vimrc"
echo "    .zshrc"
echo
read -p "Proceed? (y/N): " -n 1 -r
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
    rm ~/.bash_profile
    rm ~/.gitconfig
    rm ~/.inputrc
    rm ~/.jumpdests
    rm ~/.tmux.conf
    rm ~/.vimrc
    rm ~/.zshrc
    ln -s $SCRIPT_DIR/.bash_profile ~/.bash_profile
    ln -s $SCRIPT_DIR/.gitconfig    ~/.gitconfig
    ln -s $SCRIPT_DIR/.inputrc      ~/.inputrc
    ln -s $SCRIPT_DIR/.jumpdests    ~/.jumpdests
    ln -s $SCRIPT_DIR/.tmux.conf    ~/.tmux.conf
    ln -s $SCRIPT_DIR/.vimrc        ~/.vimrc
    ln -s $SCRIPT_DIR/.zshrc        ~/.zshrc
    echo
    echo Done.
    ls -o ~/.bash_profile
    ls -o ~/.gitconfig
    ls -o ~/.inputrc
    ls -o ~/.jumpdests
    ls -o ~/.tmux.conf
    ls -o ~/.vimrc
    ls -o ~/.zshrc
    echo
else
    echo Denied!
fi

